import Link from 'next/link'
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { jobFixture, taskFixture } from '@/test/garageFixtures'
import { applyTaskPatch } from '@/lib/maintenance/checklist'
import { Checklist } from './Checklist'
import { clearChecklistDrafts } from '@/hooks/checklistDrafts'
import { saveTaskPatchAction, loadChecklistAction, closeJobAction } from './jobs/[jobId]/actions'
vi.mock('./jobs/[jobId]/actions',()=>({saveTaskPatchAction:vi.fn(),loadChecklistAction:vi.fn(),closeJobAction:vi.fn(),correctChecklistAction:vi.fn()}))
vi.mock('@/lib/supabase/auth-browser',()=>({createAuthBrowserClient:()=>({auth:{onAuthStateChange:()=>({data:{subscription:{unsubscribe:vi.fn()}}})}})}))
vi.mock('../PrivateGarage',()=>({useGarageOwner:()=> 'owner',useGarageReconciliation:()=>{}}))
beforeEach(()=>{vi.clearAllMocks();clearChecklistDrafts('owner')})
afterEach(()=>{vi.useRealTimers();clearChecklistDrafts('owner')})
it('shows large checkboxes, visible warnings, collapsed reference and unassessed guidance',()=>{
 render(<Checklist initialJob={jobFixture({tasks:[taskFixture({warning:'Stop engine first',reference:'Manual page 4',specification:'Check source'})]})} />)
 expect(screen.getByRole('checkbox',{name:'Inspect chain'})).toHaveClass('min-h-11')
 expect(screen.getByText('Stop engine first')).toBeVisible()
 expect(screen.getByText('Manual page 4').closest('details')).not.toHaveAttribute('open')
 expect(screen.getByText(/Unassessed/)).toBeVisible()
})
it('keeps failed work visible and offers retry without claiming completion',async()=>{
 vi.mocked(saveTaskPatchAction).mockResolvedValue({ok:false,error:'save_failed',message:'Could not save'})
 render(<Checklist initialJob={jobFixture()} />)
 fireEvent.click(screen.getByRole('checkbox',{name:'Inspect chain'}))
 expect(await screen.findByRole('alert')).toHaveTextContent('Could not save')
 expect(screen.getByRole('button',{name:'Retry save'})).toBeEnabled()
 expect(screen.getByRole('checkbox')).toBeChecked()
 expect(screen.queryByText('Job completed')).not.toBeInTheDocument()
})
it('debounces notes and sends latest text after an in-flight save using its revision',async()=>{
 vi.useFakeTimers();const job=jobFixture();let finish!:(value:Awaited<ReturnType<typeof saveTaskPatchAction>>)=>void
 vi.mocked(saveTaskPatchAction).mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve})).mockImplementation(async(_id,revision,id,patch)=>({ok:true,value:applyTaskPatch({...job,revision},id,patch,'2026-10-10T12:00:00Z')}))
 render(<Checklist initialJob={job} />)
 fireEvent.click(screen.getByText('Notes and reference'))
 fireEvent.change(screen.getByLabelText('Notes: Inspect chain'),{target:{value:'First'}})
 await act(async()=>{vi.advanceTimersByTime(499) });expect(saveTaskPatchAction).not.toHaveBeenCalled()
 await act(async()=>{vi.advanceTimersByTime(1)});expect(screen.getByRole('status')).toHaveTextContent('Saving')
 fireEvent.change(screen.getByLabelText('Notes: Inspect chain'),{target:{value:'Latest'}})
 await act(async()=>{finish({ok:true,value:applyTaskPatch(job,job.tasks[0].id,{notes:'First'},'2026-10-10T12:00:00Z')})})
 expect(screen.getByLabelText('Notes: Inspect chain')).toHaveValue('Latest')
 await act(async()=>{vi.advanceTimersByTime(500)})
 expect(saveTaskPatchAction).toHaveBeenLastCalledWith(job.id,2,job.tasks[0].id,{notes:'Latest'})
 expect(screen.getByRole('status')).toHaveTextContent('Saved')
})
it('requires a reason for skipped work and excludes it from Done progress',async()=>{
 const job=jobFixture();vi.mocked(saveTaskPatchAction).mockImplementation(async(_id,_revision,id,patch)=>({ok:true,value:applyTaskPatch(job,id,patch,'2026-10-10T12:00:00Z')}))
 render(<Checklist initialJob={job} />)
 fireEvent.change(screen.getByLabelText('Task state: Inspect chain'),{target:{value:'skipped'}})
 fireEvent.click(screen.getByRole('button',{name:'Apply state'}));expect(saveTaskPatchAction).not.toHaveBeenCalled()
 fireEvent.change(screen.getByLabelText('Reason: Inspect chain'),{target:{value:'Parts missing'}})
 fireEvent.click(screen.getByRole('button',{name:'Apply state'}))
 await waitFor(()=>expect(saveTaskPatchAction).toHaveBeenCalledWith(job.id,1,job.tasks[0].id,{state:'skipped',reason:'Parts missing'}))
 expect(screen.getByText('0 of 1 Done')).toBeVisible()
})
it('retains conflict notes for copying and reloads only explicitly',async()=>{
 const job=jobFixture();vi.mocked(saveTaskPatchAction).mockResolvedValue({ok:false,error:'conflict',message:'Changed',current:{...job,revision:2}})
 vi.mocked(loadChecklistAction).mockResolvedValue(job)
 render(<Checklist initialJob={job} />)
 fireEvent.click(screen.getByText('Notes and reference'));fireEvent.change(screen.getByLabelText('Notes: Inspect chain'),{target:{value:'Unsaved observations'}})
 fireEvent.click(screen.getByRole('checkbox'))
 expect(await screen.findByRole('alert')).toHaveTextContent('This job changed on another device')
 expect(screen.getByLabelText('Notes: Inspect chain')).toHaveValue('Unsaved observations')
 expect(loadChecklistAction).not.toHaveBeenCalled()
 fireEvent.click(screen.getByRole('button',{name:'Reload saved version'}));await waitFor(()=>expect(screen.getByLabelText('Notes: Inspect chain')).toHaveValue(''))
})
it('retains failed drafts when leaving and returning to the job',async()=>{
 vi.mocked(saveTaskPatchAction).mockResolvedValue({ok:false,error:'save_failed',message:'Could not save'})
 const initial=jobFixture();const view=render(<Checklist initialJob={initial} />)
 fireEvent.click(screen.getByRole('checkbox'));await screen.findByRole('alert');view.unmount()
 render(<Checklist initialJob={initial} />);expect(screen.getByRole('checkbox')).toBeChecked();expect(screen.getByRole('alert')).toHaveTextContent('Could not save')
})
it('confirms outstanding work with date and mileage without ticking tasks',async()=>{
 const job=jobFixture();vi.mocked(closeJobAction).mockResolvedValue({ok:true,value:{...job,revision:2,status:'partial',closeReason:'manual'}})
 render(<Checklist initialJob={job} />);fireEvent.click(screen.getByRole('button',{name:'Finish job'}))
 expect(screen.getByRole('group',{name:'Completion summary'})).toHaveTextContent('Inspect chain: To do')
 expect(screen.getByLabelText('Completion date')).toHaveValue(job.date)
 expect(closeJobAction).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirm completion'}))
 await waitFor(()=>expect(closeJobAction).toHaveBeenCalledWith(job.id,1,job.date,job.mileageKm))
 expect(screen.getByRole('checkbox')).not.toBeChecked();expect(screen.getByText('Job partially completed')).toBeVisible()
})
it('acknowledges an already-applied patch after a lost response without replaying',async()=>{
 const job=jobFixture();vi.mocked(saveTaskPatchAction).mockRejectedValue(new Error('Connection lost'))
 vi.mocked(loadChecklistAction).mockResolvedValue(applyTaskPatch(job,job.tasks[0].id,{state:'done',reason:''},'2026-10-10T12:00:00Z'))
 render(<Checklist initialJob={job} />);fireEvent.click(screen.getByRole('checkbox'));await screen.findByRole('alert')
 fireEvent.click(screen.getByRole('button',{name:'Retry save'}))
 await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('Saved'))
 expect(saveTaskPatchAction).toHaveBeenCalledTimes(1);expect(screen.getByText('Job completed')).toBeVisible()
})
it('retries the exact failed patch before sending newer input',async()=>{
 const job=jobFixture();let server=job
 vi.mocked(saveTaskPatchAction).mockRejectedValueOnce(new Error('Connection lost')).mockImplementation(async(_id,_revision,id,patch)=>{server=applyTaskPatch(server,id,patch,'2026-10-10T12:00:00Z');return {ok:true,value:server}})
 vi.mocked(loadChecklistAction).mockResolvedValue(job)
 render(<Checklist initialJob={job} />);fireEvent.click(screen.getByRole('checkbox'));await screen.findByRole('alert')
 fireEvent.click(screen.getByText('Notes and reference'));fireEvent.change(screen.getByLabelText('Notes: Inspect chain'),{target:{value:'Typed after failure'}})
 fireEvent.click(screen.getByRole('button',{name:'Retry save'}))
 await waitFor(()=>expect(saveTaskPatchAction).toHaveBeenCalledTimes(2))
 expect(vi.mocked(saveTaskPatchAction).mock.calls[1]).toEqual(vi.mocked(saveTaskPatchAction).mock.calls[0])
 await waitFor(()=>expect(saveTaskPatchAction).toHaveBeenCalledTimes(3))
 expect(saveTaskPatchAction).toHaveBeenLastCalledWith(job.id,2,job.tasks[0].id,{notes:'Typed after failure'})
})
it('does not overwrite different newer server content on retry',async()=>{
 const job=jobFixture();vi.mocked(saveTaskPatchAction).mockRejectedValue(new Error('Connection lost'))
 vi.mocked(loadChecklistAction).mockResolvedValue({...job,revision:4,tasks:[taskFixture({notes:'Another device'})]})
 render(<Checklist initialJob={job} />);fireEvent.click(screen.getByText('Notes and reference'));fireEvent.change(screen.getByLabelText('Notes: Inspect chain'),{target:{value:'My private draft'}});fireEvent.click(screen.getByRole('checkbox'))
 await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'Retry save'}))
 await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('This job changed on another device'))
 expect(screen.getByLabelText('Notes: Inspect chain')).toHaveValue('My private draft');expect(saveTaskPatchAction).toHaveBeenCalledTimes(1)
})
it('warns before unload and blocks internal Next links when leaving is cancelled',async()=>{
 vi.mocked(saveTaskPatchAction).mockResolvedValue({ok:false,error:'save_failed',message:'Could not save'})
 const confirm=vi.spyOn(window,'confirm').mockReturnValue(false)
 render(<><Link href="/garage">My Garage</Link><Checklist initialJob={jobFixture()} /></>)
 fireEvent.click(screen.getByRole('checkbox'));await screen.findByRole('alert')
 const before=new Event('beforeunload',{cancelable:true});window.dispatchEvent(before);expect(before.defaultPrevented).toBe(true)
 expect(fireEvent.click(screen.getByRole('link',{name:'My Garage'}))).toBe(false)
 expect(confirm).toHaveBeenCalledWith('You have unsaved work. Leave this page?');confirm.mockRestore()
})
it('offers sign-in and keeps the form after session expiry',async()=>{
 vi.mocked(saveTaskPatchAction).mockRejectedValue(new Error('Sign in again to save.'))
 render(<Checklist initialJob={jobFixture()} />);fireEvent.click(screen.getByRole('checkbox'))
 expect(await screen.findByRole('link',{name:'Sign in again, then return to this tab'})).toHaveAttribute('target','_blank')
 expect(screen.getByRole('checkbox')).toBeChecked()
})
it('discarded owner drafts cannot be repopulated by a late successful response',async()=>{
 const job=jobFixture();let finish!:(value:Awaited<ReturnType<typeof saveTaskPatchAction>>)=>void
 vi.mocked(saveTaskPatchAction).mockImplementation(()=>new Promise(resolve=>{finish=resolve}))
 const view=render(<Checklist initialJob={job} />);fireEvent.click(screen.getByRole('checkbox'))
 clearChecklistDrafts('owner');view.unmount()
 await act(async()=>{finish({ok:true,value:applyTaskPatch(job,job.tasks[0].id,{state:'done'},'2026-10-10T12:00:00Z')})})
 render(<Checklist initialJob={job} />);expect(screen.getByRole('checkbox')).not.toBeChecked();expect(screen.getByRole('status')).toHaveTextContent('Saved')
})
it('warns and restores the current route when browser back or forward is cancelled',async()=>{
 vi.mocked(saveTaskPatchAction).mockResolvedValue({ok:false,error:'save_failed',message:'Could not save'})
 const confirm=vi.spyOn(window,'confirm').mockReturnValue(false)
 const restore=vi.spyOn(window.history,'pushState')
 render(<Checklist initialJob={jobFixture()} />);fireEvent.click(screen.getByRole('checkbox'));await screen.findByRole('alert')
 const original=window.location.href;fireEvent(window,new PopStateEvent('popstate'))
 expect(confirm).toHaveBeenCalledWith('You have unsaved work. Leave this page?')
 expect(restore).toHaveBeenCalledWith(window.history.state,'',original)
 confirm.mockRestore();restore.mockRestore()
})
it('warns before form navigation with dirty work',async()=>{
 vi.mocked(saveTaskPatchAction).mockResolvedValue({ok:false,error:'save_failed',message:'Could not save'})
 const confirm=vi.spyOn(window,'confirm').mockReturnValue(false)
 render(<><form aria-label="Navigate" action="/account"><button>Open account</button></form><Checklist initialJob={jobFixture()} /></>)
 fireEvent.click(screen.getByRole('checkbox'));await screen.findByRole('alert')
 expect(fireEvent.submit(screen.getByRole('form',{name:'Navigate'}))).toBe(false)
 expect(confirm).toHaveBeenCalledWith('You have unsaved work. Leave this page?');confirm.mockRestore()
})
it('shows completion and editable recorded details only after the last save succeeds',async()=>{
 const job=jobFixture();vi.mocked(saveTaskPatchAction).mockResolvedValue({ok:true,value:applyTaskPatch(job,job.tasks[0].id,{state:'done'},'2026-10-10T12:00:00Z')})
 render(<Checklist initialJob={job} />);fireEvent.click(screen.getByRole('checkbox'))
 expect(await screen.findByText('Job completed')).toBeVisible()
 fireEvent.click(screen.getByRole('button',{name:'Edit recorded date and mileage'}))
 expect(screen.getByLabelText('Job date')).toHaveValue(job.date)
 expect(screen.getByLabelText('Job mileage')).toHaveValue(String(job.mileageKm))
})
