'use client'
import { useRef, useState } from 'react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { GroupedList, ListRow } from '@/components/ui/grouped-list'
import type { JobView, PrivateFile, SavedResult } from '@/lib/maintenance/types'
import type { JobDetails } from '@/lib/maintenance/validation'
import { JobDetailsForm } from './QuickJobForm'
import { MaintenanceRecord } from './MaintenanceRecord'
import { ReceiptUpload } from './ReceiptUpload'
export function MaintenanceHistory({jobs,onEdit,onDelete,disabled=false,files=[],onFilesChanged,bikeId,onReload}:{bikeId?:string;onReload?:(id:string)=>Promise<JobView>;files?:PrivateFile[];onFilesChanged?:()=>void;jobs:JobView[];onEdit:(id:string,revision:number,details:JobDetails)=>Promise<SavedResult<JobView>>;onDelete:(id:string)=>Promise<SavedResult<null>>;disabled?:boolean}) {
 const [query,setQuery]=useState('');const [expanded,setExpanded]=useState<string|null>(null);const [editing,setEditing]=useState<Record<string,JobView>>({});const [opened,setOpened]=useState<Set<string>>(()=>new Set());const [removing,setRemoving]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const pending=useRef(false)
 const sorted=[...jobs].sort((a,b)=>Number(b.status==='in_progress')-Number(a.status==='in_progress')||b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id))
 const matches=sorted.filter(job=>[job.title,job.notes,...job.tasks.flatMap(task=>[task.label,task.notes])].some(text=>text.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())))
 async function remove(id:string) {if(pending.current || disabled)return;pending.current=true;setBusy(true);setError('');try {const result=await onDelete(id);if(result.ok){setRemoving(null);setExpanded(null)}else setError(result.message)}catch(error){setError(error instanceof Error?error.message:'Could not remove record.')}finally{pending.current=false;setBusy(false)}}
 function show(id:string) {setOpened(current=>new Set(current).add(id));setExpanded(expanded===id?null:id)}
 function stopEditing(id:string) {setEditing(current=>{const next={...current};delete next[id];return next})}
 function rows(items:JobView[]) {return items.map(job=><div key={job.id} hidden={!matches.some(match=>match.id===job.id)}>{matches.find(match=>(match.status==='in_progress')===(job.status==='in_progress'))?.id===job.id && <h3 className="px-4 py-3 text-sm text-muted-foreground">{job.status==='in_progress'?'Jobs in progress':'History'}</h3>}<ListRow className="min-h-[72px] break-words" label={job.title} subtitle={`${job.date} · ${job.mileageKm.toLocaleString()} km`} onClick={()=>show(job.id)} buttonProps={{'aria-label':`Show record: ${job.title}`,'aria-expanded':expanded===job.id,disabled:busy}} />{opened.has(job.id) && <div hidden={expanded!==job.id}><MaintenanceRecord job={job} />{jobs.filter(destination=>destination.tasks.some(task=>task.origin?.jobId===job.id)).map(destination=><Link key={destination.id} prefetch={false} className="mx-4 block min-h-11 py-3 text-link" href={`/garage/${destination.bikeId}/jobs/${destination.id}`}>Carried work: {destination.title}</Link>)}<Link prefetch={false} href={`/garage/${job.bikeId}/jobs/${job.id}`} className="mx-4 inline-block min-h-11 py-3 text-link">{job.status==='in_progress'?'Resume checklist':'Open checklist'}</Link>{onFilesChanged && <ReceiptUpload bikeId={job.bikeId} jobId={job.id} files={files.filter(file=>file.jobId===job.id)} onChanged={onFilesChanged} disabled={disabled || busy} />}{editing[job.id]?<div className="p-4"><JobDetailsForm job={editing[job.id]} disabled={disabled || busy} onCancel={()=>stopEditing(job.id)} onReloadSaved={onReload?()=>onReload(job.id):undefined} onReviewSaved={current=>setEditing(saved=>({...saved,[job.id]:current}))} onSave={async details=>{const result=await onEdit(job.id,editing[job.id].revision,details);if(result.ok)stopEditing(job.id);return result}} /></div>:<div className="flex flex-wrap gap-3 p-4"><Button variant="outline" className="min-h-11 whitespace-nowrap" disabled={disabled || busy} onClick={()=>{setEditing(current=>({...current,[job.id]:job}));setRemoving(null)}}>Edit record</Button><Button variant="outline" className="min-h-11 whitespace-nowrap" disabled={disabled || busy} onClick={()=>{setRemoving(job.id);setError('')}}>Remove record</Button></div>}{removing===job.id && <div className="space-y-3 p-4" role="group" aria-label="Confirm record removal"><p>Remove this maintenance record? The bike mileage will stay unchanged.</p><div className="flex flex-wrap gap-3"><Button className="min-h-11 whitespace-nowrap" disabled={busy || disabled} onClick={()=>void remove(job.id)}>Confirm removal</Button><Button className="min-h-11 whitespace-nowrap" variant="outline" disabled={busy} onClick={()=>setRemoving(null)}>Cancel removal</Button></div></div>}</div>}</div>)}
 return <div className="space-y-4">{bikeId && <details><summary className="min-h-11 cursor-pointer py-3 text-link focus-visible:outline-ring">Export records</summary><div className="flex flex-wrap gap-3 py-3">{(['json','csv'] as const).map(format=><Button key={format} asChild variant="outline" size="sm"><a href={`/api/garage/export?bikeId=${encodeURIComponent(bikeId)}&format=${format}`}>Download {format.toUpperCase()}</a></Button>)}</div><p className="text-muted-foreground">Exports include all recorded work. Download receipts separately.</p></details>}<label htmlFor="maintenance-search">Search maintenance</label><Input id="maintenance-search" className="min-h-11" value={query} onChange={event=>setQuery(event.target.value)} />{error && <p role="alert">{error}</p>}{jobs.length===0?<p>No maintenance recorded</p>:<>{matches.length===0 && <p>No matching records</p>}<GroupedList header="Maintenance records">{rows(sorted)}</GroupedList></>}</div>
}
