'use client'
import { useRef, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { GroupedList, ListRow } from '@/components/ui/grouped-list'
import type { JobView, PrivateFile, SavedResult } from '@/lib/maintenance/types'
import type { JobDetails } from '@/lib/maintenance/validation'
import { JobDetailsForm } from './QuickJobForm'
import { MaintenanceRecord } from './MaintenanceRecord'
import { ReceiptUpload } from './ReceiptUpload'
export function MaintenanceHistory({jobs,onEdit,onDelete,disabled=false,files=[],onFilesChanged,bikeId}:{bikeId?:string;files?:PrivateFile[];onFilesChanged?:()=>void;jobs:JobView[];onEdit:(id:string,revision:number,details:JobDetails)=>Promise<SavedResult<JobView>>;onDelete:(id:string)=>Promise<SavedResult<null>>;disabled?:boolean}) {
 const [query,setQuery]=useState('');const [expanded,setExpanded]=useState<string|null>(null);const [editing,setEditing]=useState<JobView|null>(null);const [removing,setRemoving]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const pending=useRef(false)
 const sorted=[...jobs].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id))
 const matches=sorted.filter(job=>[job.title,job.notes,...job.tasks.flatMap(task=>[task.label,task.notes])].some(text=>text.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())))
 async function remove(id:string) {if(pending.current || disabled)return;pending.current=true;setBusy(true);setError('');try {const result=await onDelete(id);if(result.ok){setRemoving(null);setExpanded(null)}else setError(result.message)}catch(error){setError(error instanceof Error?error.message:'Could not remove record.')}finally{pending.current=false;setBusy(false)}}
 function rows(items:JobView[]) {return items.map(job=><div key={job.id}><ListRow className="min-h-[72px] break-words" label={job.title} subtitle={`${job.date} · ${job.mileageKm.toLocaleString()} km`} onClick={()=>setExpanded(expanded===job.id?null:job.id)} buttonProps={{'aria-label':`Show record: ${job.title}`,'aria-expanded':expanded===job.id,disabled:busy}} />{expanded===job.id && <><MaintenanceRecord job={job} />{onFilesChanged && <ReceiptUpload bikeId={job.bikeId} jobId={job.id} files={files.filter(file=>file.jobId===job.id)} onChanged={onFilesChanged} disabled={disabled || busy} />}{editing?.id===job.id?<div className="p-4"><JobDetailsForm job={editing} disabled={disabled || busy} onCancel={()=>setEditing(null)} onSave={async details=>{const result=await onEdit(editing.id,editing.revision,details);if(result.ok)setEditing(null);return result}} /></div>:<div className="flex flex-wrap gap-3 p-4"><Button variant="outline" className="min-h-11 whitespace-nowrap" disabled={disabled || busy} onClick={()=>{setEditing(job);setRemoving(null)}}>Edit record</Button><Button variant="outline" className="min-h-11 whitespace-nowrap" disabled={disabled || busy} onClick={()=>{setRemoving(job.id);setError('')}}>Remove record</Button></div>}{removing===job.id && <div className="space-y-3 p-4" role="group" aria-label="Confirm record removal"><p>Remove this maintenance record? The bike mileage will stay unchanged.</p><div className="flex flex-wrap gap-3"><Button className="min-h-11 whitespace-nowrap" disabled={busy || disabled} onClick={()=>void remove(job.id)}>Confirm removal</Button><Button className="min-h-11 whitespace-nowrap" variant="outline" disabled={busy} onClick={()=>setRemoving(null)}>Cancel removal</Button></div></div>}</>}</div>)}
 return <div className="space-y-4">{bikeId && <details><summary className="min-h-11 cursor-pointer py-3 text-link focus-visible:outline-ring">Export records</summary><div className="flex flex-wrap gap-3 py-3">{(['json','csv'] as const).map(format=><Button key={format} asChild variant="outline" size="sm"><a href={`/api/garage/export?bikeId=${encodeURIComponent(bikeId)}&format=${format}`}>Download {format.toUpperCase()}</a></Button>)}</div><p className="text-muted-foreground">Exports include all recorded work. Download receipts separately.</p></details>}<label htmlFor="maintenance-search">Search maintenance</label><Input id="maintenance-search" className="min-h-11" value={query} onChange={event=>setQuery(event.target.value)} />{error && <p role="alert">{error}</p>}{jobs.length===0?<p>No maintenance recorded</p>:matches.length===0?<p>No matching records</p>:<>{matches.some(job=>job.status==='in_progress') && <GroupedList header="Active jobs">{rows(matches.filter(job=>job.status==='in_progress'))}</GroupedList>}{matches.some(job=>job.status!=='in_progress') && <GroupedList header="History">{rows(matches.filter(job=>job.status!=='in_progress'))}</GroupedList>}</>}</div>
}
