import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { expect, it, vi } from 'vitest'
import { bikeFixture, templateFixture, jobFixture } from '@/test/garageFixtures'
import { TemplatePicker } from './TemplatePicker'
const custom=()=>templateFixture({id:'personal',kind:'custom',source:null})
function setup(templates=[custom()]) {const props={bike:bikeFixture(),templates,previous:null,onStart:vi.fn().mockResolvedValue({ok:true,value:jobFixture()}),onSave:vi.fn(),onReloadPrevious:vi.fn(),onConfirmCoverage:vi.fn()};render(<TemplatePicker {...props}/>);return props}
it('groups personal work on an unlisted bike and prints without creating a job',()=>{const p=setup();expect(screen.getByText('My templates')).toBeInTheDocument();expect(screen.getByText(/Due status is unknown/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'Print blank checklist'})).toHaveAttribute('href',`/garage/${p.bike.id}/templates/personal/print`);expect(p.onStart).not.toHaveBeenCalled();expect(screen.getByRole('checkbox')).not.toBeChecked()})
it('starts fresh todo tasks with manually entered zero mileage',async()=>{const p=setup();fireEvent.click(screen.getByRole('checkbox'));fireEvent.change(screen.getByLabelText('Checklist date'),{target:{value:'2026-10-10'}});fireEvent.change(screen.getByLabelText('Checklist mileage'),{target:{value:'0'}});fireEvent.click(screen.getByRole('button',{name:'Start checklist'}));await waitFor(()=>expect(p.onStart).toHaveBeenCalledTimes(1));const [draft,ids,carry]=p.onStart.mock.calls[0];expect(draft.mileageKm).toBe(0);expect(draft.tasks[0]).toMatchObject({state:'todo',notes:'',origin:null,doneAt:null});expect(ids).toEqual(['personal']);expect(carry).toBeNull()})
it('hides mismatched source work and prompts exact coverage confirmation',()=>{const bike=bikeFixture({motorcycleId:'b4660699-fb60-4f70-b5c0-2023cb650a00',year:2023,market:'Europe'});const template=templateFixture({motorcycleId:bike.motorcycleId,years:[2023],markets:['Europe'],variants:['CB650RA']});const confirm=vi.fn();render(<TemplatePicker bike={bike} templates={[template]} previous={null} onSave={vi.fn()} onStart={vi.fn()} onReloadPrevious={vi.fn()} onConfirmCoverage={confirm}/>);expect(screen.queryByRole('checkbox')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Confirm bike coverage'}));expect(confirm).toHaveBeenCalledOnce()})
it('retains inputs and retry identifiers after a failed save',async()=>{const p=setup();p.onStart.mockResolvedValue({ok:false,error:'save_failed',message:'Retry save'});fireEvent.click(screen.getByRole('checkbox'));fireEvent.change(screen.getByLabelText('Checklist date'),{target:{value:'2026-10-10'}});fireEvent.change(screen.getByLabelText('Checklist mileage'),{target:{value:'12'}});fireEvent.click(screen.getByRole('button',{name:'Start checklist'}));await screen.findByText('Retry save');const first=p.onStart.mock.calls[0][0];fireEvent.click(screen.getByRole('button',{name:'Start checklist'}));await waitFor(()=>expect(p.onStart).toHaveBeenCalledTimes(2));expect(p.onStart.mock.calls[1][0]).toEqual(first);expect(screen.getByLabelText('Checklist mileage')).toHaveValue('12')})
it('lets changed definitions be reloaded while retaining entered date and mileage',async()=>{
 const reload=vi.fn().mockResolvedValue(undefined)
 render(<TemplatePicker bike={bikeFixture()} templates={[custom()]} previous={null} onStart={vi.fn().mockResolvedValue({ok:false,error:'conflict',message:'Template changed'})} onSave={vi.fn()} onReloadPrevious={vi.fn()} onReloadTemplates={reload} onConfirmCoverage={vi.fn()}/>);
 fireEvent.click(screen.getByRole('checkbox'));fireEvent.change(screen.getByLabelText('Checklist date'),{target:{value:'2026-10-10'}});fireEvent.change(screen.getByLabelText('Checklist mileage'),{target:{value:'12'}});fireEvent.click(screen.getByRole('button',{name:'Start checklist'}));await screen.findByText('Template changed');fireEvent.click(screen.getByRole('button',{name:'Reload templates'}));await waitFor(()=>expect(reload).toHaveBeenCalledOnce());await waitFor(()=>expect(screen.getByRole('checkbox')).not.toBeChecked());fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByLabelText('Checklist date')).toHaveValue('2026-10-10');expect(screen.getByLabelText('Checklist mileage')).toHaveValue('12')
})
