'use client'
import { useState } from 'react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import type { BikeView } from '@/lib/garageBikes'
import type { JobDraft, JobView, SavedResult, Template } from '@/lib/maintenance/types'
import { createTasks } from '@/lib/maintenance/checklist'
import { combineTemplates, matchesCoverage } from '@/lib/maintenance/templateValidation'
import type { CarrySelection } from '@/lib/maintenance/carryover'
import { toKilometres } from '@/lib/maintenance/distance'
import { CarryOverPicker } from './CarryOverPicker'
import { CustomTemplateForm } from './CustomTemplateForm'
const groups=[['scheduled','Scheduled service'],['time_based','Time-based work'],['individual','Individual tasks'],['custom','My templates']] as const
export function TemplatePicker({bike,templates,previous,onStart,onSave,onReloadPrevious,onReloadTemplates,onConfirmCoverage,coverage=[],disabled=false}:{bike:BikeView;templates:Template[];previous:JobView|null;onStart:(draft:JobDraft,ids:string[],carry:CarrySelection|null)=>Promise<SavedResult<JobView>>;onSave:(template:Template)=>Promise<Template>;onReloadPrevious:()=>Promise<JobView|null>;onReloadTemplates?:()=>Promise<void>;onConfirmCoverage:()=>void;coverage?:Template[];disabled?:boolean}) {
 const available=templates.filter(template=>matchesCoverage(template,bike))
 const [selected,setSelected]=useState<string[]>([]),[editing,setEditing]=useState<Template|null|undefined>(undefined)
 const [date,setDate]=useState(''),[mileage,setMileage]=useState(''),[unit,setUnit]=useState<'km'|'miles'>('km')
 const [carry,setCarry]=useState<CarrySelection|null>(null),[source,setSource]=useState<JobView|null|undefined>(undefined),[sourceConflict,setSourceConflict]=useState(false)
 const [pickerVersion,setPickerVersion]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState<JobView|null>(null)
 const [draft,setDraft]=useState<JobDraft|null>(null)
 const [jobId,setJobId]=useState(()=>crypto.randomUUID())
 const selectedTemplates=selected.map(id=>available.find(t=>t.id===id)).filter((t):t is Template=>Boolean(t))
 function choose(id:string,checked:boolean) {setSelected(checked?[...selected,id]:selected.filter(value=>value!==id));setDraft(null);setSaved(null)}
 async function start() {
  if(busy||disabled)return;setBusy(true);setError('');setSaved(null)
  try {
   if(!draft && (!date || !mileage.trim() || selectedTemplates.length!==selected.length))throw new Error('Choose a template and enter date and mileage.')
   const template=draft?.template??combineTemplates(selectedTemplates)
   const next=draft??{id:jobId,bikeId:bike.id,title:template.title,date,mileageKm:toKilometres(Number(mileage),unit),template,tasks:createTasks(template,()=>crypto.randomUUID()),notes:'',parts:'',performer:'',costMinor:null,currency:null}
   setDraft(next)
   const result=await onStart(next,selected,carry)
   if(!result.ok){setError(result.message);if(result.error==='conflict' && result.current && carry)setSourceConflict(true);return}
   setSaved(result.value);setDraft(null);setJobId(crypto.randomUUID());setSelected([]);setCarry(null);setSource(undefined);setSourceConflict(false);setPickerVersion(v=>v+1)
  }catch(error){setError(error instanceof Error?error.message:'Could not start checklist. Try again.')}
  finally{setBusy(false)}
 }
 return <section aria-label="Maintenance templates" className="space-y-4"><h3 className="text-xl font-semibold">Start from a template</h3><p>Choose work deliberately. Due status is unknown: history, anniversary and early-service reset rules are not established. Pre-ride checks still apply.</p>{bike.motorcycleId && (!bike.year||!bike.market||!bike.variant||!available.some(t=>t.kind!=='custom'))&&<div className="space-y-2"><p>Verified coverage needs the exact year, market and variant. Confirm them in Bike details.</p>{coverage.length>0&&<p className="break-words">Reviewed coverage: {Array.from(new Set(coverage.flatMap(t=>t.years))).join(', ')}; {Array.from(new Set(coverage.flatMap(t=>t.markets))).join(', ')}; {Array.from(new Set(coverage.flatMap(t=>t.variants))).join(', ')}.</p>}<Button type="button" variant="outline" className="min-h-11" onClick={onConfirmCoverage}>Confirm bike coverage</Button></div>}<fieldset disabled={disabled||busy} className="space-y-4">{groups.map(([kind,label])=><details key={kind} className="space-y-2" open={kind==='scheduled'||(kind==='custom'&&!available.some(t=>t.kind!=='custom'))}><summary className="min-h-11 cursor-pointer py-3 font-semibold">{label}</summary>{available.filter(t=>t.kind===kind).length===0&&<p className="text-muted-foreground">No templates available.</p>}{available.filter(t=>t.kind===kind).map(template=><div key={template.id} className="rounded-[14px] bg-input p-3"><label className="flex min-h-11 items-center gap-3"><input className="h-5 w-5 shrink-0" type="checkbox" checked={selected.includes(template.id)} onChange={event=>choose(template.id,event.target.checked)} /><span className="break-words">{template.title}</span></label>{template.kind==='scheduled'&&template.intervalMonths!==null&&<p>{template.intervalKm?.toLocaleString('en-GB')} km or {template.intervalMonths} months, whichever comes first.</p>}<details><summary className="min-h-11 cursor-pointer py-3">Source and tasks</summary><p className="break-words">{template.source??'Personal template; safety guidance unassessed.'}</p><p>{template.frequency==='once'?'One-off first service':template.frequency==='recurring'?'Recurring source schedule; select the applicable column':'Selected on demand'}</p>{template.tasks.map(task=><div key={task.key} className="my-3 break-words"><p>{task.label}</p><p>{task.warning??'Safety guidance unassessed.'}</p><p>{task.reference}</p></div>)}</details><Link prefetch={false} className="inline-block min-h-11 py-3 text-link" href={`/garage/${bike.id}/templates/${encodeURIComponent(template.id)}/print`}>Print blank checklist</Link>{kind==='custom'&&<Button type="button" variant="outline" className="min-h-11" onClick={()=>setEditing(template)}>Edit template</Button>}</div>)}</details>)}<Button type="button" variant="outline" className="min-h-11" onClick={()=>setEditing(null)}>Create personal template</Button>
 {selectedTemplates.length>0&&<div className="space-y-3"><p>Review warnings before beginning. The 2008 manual recommends a dealer road test after periodic maintenance. For 2023 CB650RA, evaporative-system inspection is a separate conditional choice for confirmed ED types at 24,000 or 48,000 km.</p>{selectedTemplates.flatMap(t=>t.tasks).filter((t,i,all)=>all.findIndex(x=>x.key===t.key)===i).map(task=><p key={task.key} className="break-words">{task.label}: {task.warning??'Safety guidance unassessed.'}</p>)}<label className="block">Checklist date<Input type="date" className="min-h-11" required value={date} onChange={e=>{setDate(e.target.value);setDraft(null)}} /></label><label className="block">Checklist mileage<Input className="min-h-11" required value={mileage} onChange={e=>{setMileage(e.target.value);setDraft(null)}} /></label><label className="block">Checklist mileage unit<select className="min-h-11 bg-input px-3" value={unit} onChange={e=>{const next=e.target.value as 'km'|'miles';if(mileage.trim()&&Number.isFinite(Number(mileage)))setMileage(String(Number(mileage)*(next==='miles'?1/1.609344:1.609344)));setUnit(next);setDraft(null)}}><option value="km">Kilometres</option><option value="miles">Miles</option></select></label><CarryOverPicker key={pickerVersion} previous={source===undefined?previous:source} onChange={choice=>{setCarry(choice);if(choice)setSource(source===undefined?previous:source)}} /><Button type="button" className="min-h-11" onClick={()=>void start()}>{busy?'Starting…':'Start checklist'}</Button></div>}
 {error&&<><p role="alert">{error}</p>{draft&&<Button type="button" variant="outline" className="min-h-11" onClick={()=>void start()}>Retry previous start</Button>}{!sourceConflict&&onReloadTemplates&&<Button type="button" variant="outline" className="min-h-11" onClick={async()=>{setBusy(true);try{await onReloadTemplates();setSelected([]);setError('Templates reloaded. Retry the previous start to recover a saved checklist, or select work again; date and mileage were retained.')}catch(error){setError(error instanceof Error?error.message:'Could not reload templates.')}finally{setBusy(false)}}}>Reload templates</Button>}</>}{sourceConflict&&<Button type="button" variant="outline" className="min-h-11" onClick={async()=>{setBusy(true);try{setSource(await onReloadPrevious());setCarry(null);setPickerVersion(v=>v+1);setSourceConflict(false);setError('Previous activity reloaded. Select carry work again if needed.')}catch(error){setError(error instanceof Error?error.message:'Could not reload previous activity.')}finally{setBusy(false)}}}>Reload previous activity</Button>}{saved&&<p role="status">Checklist started. <Link prefetch={false} className="text-link" href={`/garage/${bike.id}/jobs/${saved.id}`}>Open checklist</Link></p>}</fieldset>{editing!==undefined&&<CustomTemplateForm key={editing?.id??'new'} initial={editing??undefined} onSave={onSave} onCancel={()=>setEditing(undefined)} />}</section>
}
