import assert from 'node:assert/strict'
import { createClient } from '@supabase/supabase-js'
import { createLocalTestClients, loadGarageTestEnv } from './garage-test-env'
import type { Json, TablesInsert } from '../src/types/database.types'
import type { JobDraft } from '../src/lib/maintenance/types'
import { closeJob, saveTaskPatch, createQuickJob, deleteJob, editJobDetails, getJob, listJobs } from '../src/lib/maintenance/jobsRepository.server'
import { jobFixture, taskFixture, templateFixture } from '../src/test/garageFixtures'
import { addBike, archiveBike, editBike, getBike, importSelectedModels, listBikes, removeBike } from '../src/lib/garageRepository.server'

async function main() {
  const { a, b, userA, userB, modelId, cleanup } = await createLocalTestClients()
  const accountA = { client: a, userId: userA }
  const accountB = { client: b, userId: userB }
  const input = { motorcycleId: modelId, nickname: '', make: 'Honda', model: 'CB650RA', year: 2023, variant: '', market: '', registration: '', mileageKm: 0 }
  try {
    const id = crypto.randomUUID()
    const bike = await addBike(accountA, input, id)
    assert.equal(bike.id, id)
    assert.equal(bike.modelReferenceUrl, '/bikes/honda-cb650ra-2023')
    assert.ok(bike.libraryImageUrl)
    assert.deepEqual(await addBike(accountA, input, id), bike)
    assert.equal((await listBikes(accountA)).length, 1)
    assert.deepEqual(await listBikes(accountB), [])
    assert.equal(await getBike(accountB, id), null)
    assert.deepEqual((await b.from('garage_bikes').select('*').eq('id', id)).data, [])
    assert.ok((await b.from('garage_bikes').insert({ id: crypto.randomUUID(), owner_id: userA, make: 'Honda', model: 'CB650RA' })).error)
    assert.ok((await a.from('garage_bikes').update({ owner_id: userB }).eq('id', id)).error)
    for (const result of [await b.from('garage_bikes').update({ nickname: 'Stolen' }).eq('id', id).select(), await b.from('garage_bikes').delete().eq('id', id).select()]) {
      assert.deepEqual(result.data, [])
    }
    await assert.rejects(editBike(accountB, id, input))
    await assert.rejects(archiveBike(accountB, id, true))
    await assert.rejects(removeBike(accountB, id))
    const { url, anonKey } = loadGarageTestEnv()
    const anonymous = createClient(url, anonKey, { auth: { persistSession: false } })
    assert.ok((await anonymous.from('garage_bikes').select('*')).error)
    assert.ok((await anonymous.from('garage_bikes').insert({ id: crypto.randomUUID(), owner_id: userA, make: 'Honda', model: 'CB650RA' })).error)
    assert.ok((await anonymous.from('garage_bikes').update({ nickname: 'Stolen' }).eq('id', id)).error)
    assert.ok((await anonymous.from('garage_bikes').delete().eq('id', id)).error)
    for (const invalid of [{ mileage_km: -1 }, { year: 1884 }, { make: '' }, { make: 'a' + ' '.repeat(120) }, { nickname: 'a'.repeat(81) }]) {
      assert.ok((await a.from('garage_bikes').insert({ id: crypto.randomUUID(), owner_id: userA, make: 'Honda', model: 'Custom', ...invalid })).error)
    }
    await assert.rejects(addBike(accountA, { ...input, year: 2024 }, crypto.randomUUID()))
    await assert.rejects(editBike(accountA, id, { ...input, year: 2022 }))
    const unknown = await addBike(accountA, { ...input, year: null }, crypto.randomUUID())
    assert.ok(unknown.libraryImageUrl)
    assert.equal(unknown.modelReferenceUrl, null)
    await addBike(accountA, input, crypto.randomUUID())
    assert.equal((await listBikes(accountA)).length, 3)
    const changed = await editBike(accountA, id, { ...input, nickname: 'Mine' })
    assert.equal(changed.nickname, 'Mine')
    await archiveBike(accountA, id, true)
    assert.equal((await listBikes(accountA, true)).length, 1)
    await archiveBike(accountA, id, false)
    assert.equal((await listBikes(accountA, true)).length, 0)
    const firstImport = await importSelectedModels(accountA, [modelId, modelId])
    const secondImport = await importSelectedModels(accountA, [modelId])
    assert.equal(firstImport.length, 1)
    assert.equal(firstImport[0].id, secondImport[0].id)
    const draft = (mileageKm = 12000, bikeId = id): JobDraft => ({...jobFixture(),id:crypto.randomUUID(),bikeId,mileageKm,
      tasks:[taskFixture({id:crypto.randomUUID(),key:null,state:'done',doneAt:'2026-10-10T10:00:00Z'})]})
    const firstDraft = draft()
    const first = await createQuickJob(accountA,firstDraft)
    assert.ok(first.ok)
    assert.equal(first.value.status,'completed')
    assert.equal(first.value.closeReason,'all_done')
    assert.equal((await getBike(accountA,id))?.mileageKm,12000)
    assert.deepEqual(await createQuickJob(accountA,firstDraft),first)
    const retries = await Promise.all([createQuickJob(accountA,firstDraft),createQuickJob(accountA,firstDraft)])
    assert.deepEqual(retries,[first,first])
    assert.equal((await listJobs(accountA,id)).length,1)
    assert.deepEqual(await listJobs(accountB,id),[])
    assert.equal(await getJob(accountB,firstDraft.id),null)
    assert.deepEqual((await b.from('maintenance_jobs').select('*').eq('id',firstDraft.id)).data,[])
    assert.equal((await createQuickJob(accountB,draft(123,id))).ok,false)
    assert.deepEqual(await editJobDetails(accountB,firstDraft.id,1,firstDraft),{ok:false,error:'not_found',message:'Job or bike not found'})
    assert.equal((await deleteJob(accountB,firstDraft.id)).ok,false)
    assert.ok((await b.from('maintenance_jobs').insert({id:crypto.randomUUID(),owner_id:userB,bike_id:id,title:'Foreign bike',job_date:'2026-10-10',mileage_km:0,tasks:firstDraft.tasks as unknown as Json,status:'completed',close_reason:'all_done',closed_at:'2026-10-10T10:00:00Z'})).error)
    assert.ok((await a.from('maintenance_jobs').update({owner_id:userB}).eq('id',firstDraft.id)).error)
    for (const response of [await b.from('maintenance_jobs').update({title:'Stolen'}).eq('id',firstDraft.id).select(),await b.from('maintenance_jobs').delete().eq('id',firstDraft.id).select()]) assert.deepEqual(response.data,[])
    for (const response of [await anonymous.from('maintenance_jobs').select('*'),await anonymous.rpc('create_quick_job',{p_draft:firstDraft as unknown as Json}),await anonymous.rpc('edit_job_details',{p_job_id:firstDraft.id,p_expected_revision:1,p_details:firstDraft as unknown as Json})]) assert.ok(response.error)
    for (const response of [await anonymous.from('maintenance_jobs').insert({id:crypto.randomUUID(),owner_id:userA,bike_id:id,title:'Anonymous',job_date:'2026-10-10',mileage_km:0,tasks:firstDraft.tasks as unknown as Json,status:'completed',close_reason:'all_done',closed_at:'2026-10-10T10:00:00Z'}),await anonymous.from('maintenance_jobs').update({title:'Anonymous'}).eq('id',firstDraft.id),await anonymous.from('maintenance_jobs').delete().eq('id',firstDraft.id)]) assert.ok(response.error)
    const historical = {...draft(0),date:'2000-01-01',costMinor:0,currency:'EUR'}
    assert.ok((await createQuickJob(accountA,historical)).ok)
    assert.equal((await getBike(accountA,id))?.mileageKm,12000)
    const changedJob = await editJobDetails(accountA,firstDraft.id,1,{...firstDraft,mileageKm:100,notes:'Edited <b>plain</b>',costMinor:0,currency:'EUR'})
    assert.ok(changedJob.ok)
    assert.equal(changedJob.value.revision,2)
    assert.equal(changedJob.value.closedAt,first.value.closedAt)
    assert.equal((await getBike(accountA,id))?.mileageKm,12000)
    const stale = await editJobDetails(accountA,firstDraft.id,1,{...firstDraft,title:'Stale edit'})
    assert.ok(!stale.ok && stale.error==='conflict')
    assert.equal(stale.current?.revision,2)
    assert.equal(stale.current?.notes,'Edited <b>plain</b>')
    assert.deepEqual(await createQuickJob(accountA,firstDraft),changedJob)
    const otherBike = await addBike(accountA,{...input,motorcycleId:null,model:'Other'},crypto.randomUUID())
    assert.equal((await createQuickJob(accountA,{...firstDraft,bikeId:otherBike.id})).ok,false)
    const races = await Promise.all([createQuickJob(accountA,draft(14000)),createQuickJob(accountA,draft(13000))])
    assert.ok(races.every(r=>r.ok))
    assert.equal((await getBike(accountA,id))?.mileageKm,14000)
    const editRace = await Promise.all([editJobDetails(accountA,firstDraft.id,2,{...firstDraft,notes:'Device one'}),editJobDetails(accountA,firstDraft.id,2,{...firstDraft,notes:'Device two'})])
    assert.equal(editRace.filter(r=>r.ok).length,1)
    assert.equal(editRace.filter(r=>!r.ok && r.error==='conflict').length,1)
    assert.equal((await getJob(accountA,firstDraft.id))?.revision,3)
    const tableRow: TablesInsert<'maintenance_jobs'> = {id:crypto.randomUUID(),owner_id:userA,bike_id:id,title:'Table validation',job_date:'2026-10-10',mileage_km:1,tasks:firstDraft.tasks as unknown as Json,status:'completed',close_reason:'all_done',closed_at:'2026-10-10T10:00:00Z'}
    const invalidTasks = [null,{},[],[{}],Array(101).fill(firstDraft.tasks[0]),[firstDraft.tasks[0],firstDraft.tasks[0]]]
    for (const patch of [{id:'bad'},{label:''},{label:' '},{label:'x'.repeat(161)},{action:'repair'},{action:null},{state:'fake'},{state:null},{state:'todo'},{state:'skipped',reason:''},{state:'not_applicable',reason:' '},{doneAt:null},{doneAt:'nonsense'},{doneAt:'2026-02-30T10:00:00Z'},{notes:null},{notes:'x'.repeat(4001)},{reason:'x'.repeat(501)},{key:3},{warning:2},{safety:'blue'},{origin:{jobId:'bad',taskId:'bad',previousNotes:''}}]) invalidTasks.push([{...firstDraft.tasks[0],...patch}])
    for (const tasks of invalidTasks) {
      const rpcResult = await a.rpc('create_quick_job',{p_draft:{...draft(),tasks} as unknown as Json})
      assert.ok(rpcResult.error,`RPC accepted invalid tasks ${JSON.stringify(tasks).slice(0,100)}`)
      const directResult = await a.from('maintenance_jobs').insert({...tableRow,id:crypto.randomUUID(),tasks:tasks as Json})
      assert.ok(directResult.error,`Table accepted invalid tasks ${JSON.stringify(tasks).slice(0,100)}`)
      assert.ok((await a.from('maintenance_jobs').update({tasks:tasks as Json}).eq('id',firstDraft.id)).error)
    }
    assert.equal((await getBike(accountA,id))?.mileageKm,14000)
    assert.equal((await getJob(accountA,firstDraft.id))?.revision,3)
    for (const patch of [{status:'in_progress',close_reason:null,closed_at:null},{status:'partial',close_reason:'all_done'},{status:'partial',close_reason:'manual'},{status:'completed',close_reason:null},{template_id:'fake'},{cost_minor:9007199254740992,currency:'EUR'},{cost_minor:0,currency:null}]) assert.ok((await a.from('maintenance_jobs').insert({...tableRow,...patch,id:crypto.randomUUID()})).error)
    const todo = {...firstDraft.tasks[0],state:'todo',doneAt:null}
    assert.ok((await a.from('maintenance_jobs').insert({...tableRow,id:crypto.randomUUID(),tasks:[todo] as Json,status:'completed',close_reason:'manual'})).error)
    const partialId = crypto.randomUUID()
    assert.equal((await a.from('maintenance_jobs').insert({...tableRow,id:partialId,tasks:[todo] as Json,status:'partial',close_reason:'manual'})).error,null)
    const excluded = {...todo,state:'not_applicable',reason:'No fitted part'}
    assert.equal((await a.from('maintenance_jobs').insert({...tableRow,id:crypto.randomUUID(),tasks:[excluded] as Json,status:'completed',close_reason:'manual'})).error,null)
    const template = templateFixture()
    assert.equal((await a.from('maintenance_jobs').insert({...tableRow,id:crypto.randomUUID(),tasks:[todo] as Json,status:'in_progress',close_reason:null,closed_at:null,template_id:template.id,template_version:1,template_snapshot:template as unknown as Json})).error,null)
    for (const templatePatch of [{version:0},{tasks:[]},{kind:'fake'},{years:[null]}]) assert.ok((await a.from('maintenance_jobs').insert({...tableRow,id:crypto.randomUUID(),template_id:template.id,template_version:1,template_snapshot:{...template,...templatePatch} as unknown as Json})).error)
    for (const detailsPatch of [{date:'2026-02-30'},{mileageKm:'1'},{mileageKm:0.0001},{title:null},{costMinor:0,currency:null},{costMinor:1.5,currency:'EUR'},{costMinor:9007199254740992,currency:'EUR'}]) {
      assert.ok((await a.rpc('edit_job_details',{p_job_id:firstDraft.id,p_expected_revision:3,p_details:{...firstDraft,...detailsPatch} as unknown as Json})).error)
      assert.ok((await a.rpc('create_quick_job',{p_draft:{...draft(),...detailsPatch} as unknown as Json})).error)
    }
    const zeroBike = await addBike(accountA,{...input,motorcycleId:null,model:'Zero',mileageKm:null},crypto.randomUUID())
    assert.ok((await createQuickJob(accountA,draft(0,zeroBike.id))).ok)
    assert.equal((await getBike(accountA,zeroBike.id))?.mileageKm,0)
    await archiveBike(accountA,otherBike.id,true)
    assert.equal((await createQuickJob(accountA,draft(1,otherBike.id))).ok,false)
    assert.ok((await deleteJob(accountA,firstDraft.id)).ok)
    assert.equal((await getBike(accountA,id))?.mileageKm,14000)
    const checklistId=crypto.randomUUID(), taskId=crypto.randomUUID()
    const checklistRow={...tableRow,id:checklistId,tasks:[{...todo,id:taskId}] as Json,status:'in_progress',close_reason:null,closed_at:null}
    assert.ifError((await a.from('maintenance_jobs').insert(checklistRow)).error)
    const completed=await saveTaskPatch(accountA,checklistId,1,taskId,{state:'done',notes:'Saved atomically'})
    assert.ok(completed.ok);assert.equal(completed.value.status,'completed');assert.equal(completed.value.closeReason,'all_done');assert.equal(completed.value.revision,2)
    assert.equal(completed.value.date,checklistRow.job_date)
    const repeated=await saveTaskPatch(accountA,checklistId,2,taskId,{state:'done'})
    assert.ok(repeated.ok);assert.equal(repeated.value.tasks[0].doneAt,completed.value.tasks[0].doneAt);assert.equal(repeated.value.closedAt,completed.value.closedAt)
    const reopened=await saveTaskPatch(accountA,checklistId,3,taskId,{state:'todo'})
    assert.ok(reopened.ok);assert.equal(reopened.value.status,'in_progress');assert.equal(reopened.value.closedAt,null);assert.equal(reopened.value.tasks[0].doneAt,null);assert.equal(reopened.value.tasks[0].notes,'Saved atomically')
    assert.ok((await a.rpc('save_task_patch',{p_job_id:checklistId,p_expected_revision:4,p_task_id:taskId,p_patch:{state:'fake'}})).error)
    assert.ok((await a.rpc('save_task_patch',{p_job_id:checklistId,p_expected_revision:4,p_task_id:taskId,p_patch:{state:'not_applicable',reason:' '}})).error)
    assert.ok((await a.rpc('save_task_patch',{p_job_id:checklistId,p_expected_revision:4,p_task_id:taskId,p_patch:{notes:null}})).error)
    assert.ok((await a.rpc('save_task_patch',{p_job_id:checklistId,p_expected_revision:4,p_task_id:crypto.randomUUID(),p_patch:{notes:'Unknown'}})).error)
    assert.equal((await saveTaskPatch(accountB,checklistId,4,taskId,{})).ok,false)
    assert.equal((await closeJob(accountB,checklistId,4,'2000-01-01',0)).ok,false)
    for(const response of [await anonymous.rpc('save_task_patch',{p_job_id:checklistId,p_expected_revision:4,p_task_id:taskId,p_patch:{}}),await anonymous.rpc('close_maintenance_job',{p_job_id:checklistId,p_expected_revision:4,p_date:'2000-01-01',p_mileage:0})]) assert.ok(response.error)
    const patchRace=await Promise.all([saveTaskPatch(accountA,checklistId,4,taskId,{state:'done',notes:'Device one'}),saveTaskPatch(accountA,checklistId,4,taskId,{state:'done',notes:'Device two'})])
    assert.equal(patchRace.filter(result=>result.ok).length,1);assert.equal(patchRace.filter(result=>!result.ok && result.error==='conflict').length,1)
    const winner=patchRace.find(result=>result.ok);assert.ok(winner?.ok)
    const loser=patchRace.find(result=>!result.ok);assert.ok(loser && !loser.ok);assert.equal(loser.current?.tasks[0].notes,winner.value.tasks[0].notes)
    assert.equal((await getJob(accountA,checklistId))?.closedAt,winner.value.closedAt)
    const pending=await saveTaskPatch(accountA,checklistId,5,taskId,{state:'skipped',reason:'Waiting for parts'})
    assert.ok(pending.ok);assert.equal(pending.value.status,'in_progress')
    const manual=await closeJob(accountA,checklistId,6,'2000-01-01',0)
    assert.ok(manual.ok);assert.equal(manual.value.status,'partial');assert.equal(manual.value.closeReason,'manual');assert.equal(manual.value.date,'2000-01-01');assert.equal(manual.value.mileageKm,0)
    assert.equal((await getBike(accountA,id))?.mileageKm,14000)
    const excludedManual=await saveTaskPatch(accountA,checklistId,7,taskId,{state:'not_applicable',reason:'No fitted part'})
    assert.ok(excludedManual.ok);assert.equal(excludedManual.value.status,'completed');assert.equal(excludedManual.value.closedAt,manual.value.closedAt)
    const manualUncheck=await saveTaskPatch(accountA,checklistId,8,taskId,{state:'todo',notes:'Still closed'})
    assert.ok(manualUncheck.ok);assert.equal(manualUncheck.value.status,'partial');assert.equal(manualUncheck.value.closedAt,manual.value.closedAt)
    const noteOnly=await saveTaskPatch(accountA,checklistId,9,taskId,{notes:'Changed notes'})
    assert.ok(noteOnly.ok);assert.equal(noteOnly.value.closedAt,manual.value.closedAt)
    const staleChecklist=await saveTaskPatch(accountA,checklistId,9,taskId,{notes:'Stale'})
    assert.ok(!staleChecklist.ok && staleChecklist.error==='conflict');assert.equal(staleChecklist.current?.tasks[0].notes,'Changed notes')
    assert.ok((await a.rpc('close_maintenance_job',{p_job_id:checklistId,p_expected_revision:10,p_date:'2000-01-01',p_mileage:0.0001})).error)
    assert.equal((await getJob(accountA,checklistId))?.revision,10)
    console.log('PASS: checklist atomic last Done/race, repeated timestamps, automatic reopen, manual partial/exclusions/notes, historical mileage, stale conflict and owner/anonymous denial')
    console.log('PASS: jobs owner/anonymous denial, task/template/closure direct-write validation, calendar/cost validation, atomic mileage max, historical zero/edit/delete, stable and concurrent retries, create/edit races and stale revisions')
    const performed={...draft(),title:'Replaced oil',tasks:[taskFixture({id:crypto.randomUUID(),key:null,label:'Replaced oil',action:'other',state:'done',doneAt:'2026-10-10T10:00:00Z'})]}
    const logged=await createQuickJob(accountA,performed);assert.ok(logged.ok)
    const corrected=await editJobDetails(accountA,performed.id,1,{...performed,title:'Inspected chain'})
    assert.ok(corrected.ok);assert.equal(corrected.value.tasks[0].label,'Inspected chain')
    assert.deepEqual({...corrected.value.tasks[0],label:'Replaced oil'},performed.tasks[0])
    assert.equal(corrected.value.closedAt,logged.value.closedAt)
    const lost=await editJobDetails(accountA,performed.id,1,{...performed,title:'Inspected chain'})
    assert.ok(lost.ok);assert.equal(lost.value.revision,2)
    const many={...draft(),tasks:[...performed.tasks,{...performed.tasks[0],id:crypto.randomUUID(),label:'Other work'}]}
    assert.ok((await createQuickJob(accountA,many)).ok)
    const retitled=await editJobDetails(accountA,many.id,1,{...many,title:'Two tasks'})
    assert.ok(retitled.ok);assert.deepEqual(retitled.value.tasks,many.tasks)
    const staleDetails=await getBike(accountA,id);assert.ok(staleDetails)
    // A distinct client sharing the owner's session represents another device.
    const device=createClient(url,anonKey,{auth:{persistSession:false,autoRefreshToken:false}})
    const {data:{session}}=await a.auth.getSession();assert.ok(session);assert.ifError((await device.auth.setSession(session)).error)
    assert.ok((await createQuickJob({client:device,userId:userA},draft(15000))).ok)
    assert.equal((await editBike(accountA,id,{...staleDetails,nickname:'Only nickname',mileageEdited:false})).mileageKm,15000)
    assert.equal((await editBike(accountA,id,{...staleDetails,mileageKm:11000,mileageEdited:true})).mileageKm,11000)
    console.log('PASS: atomic performed-work correction, unchanged completion facts, multi-task title only, matching lost-response acknowledgment, other-device mileage preservation and explicit lowering')
    await removeBike(accountA, id)
    assert.equal(await getBike(accountA, id), null)
    console.log('PASS: local ownership, anonymous denial, validation, same-model bikes, year scope, stable retries, import retries, archive/restore, delete')
  } finally { await cleanup() }
}
main().catch(error => { console.error(error instanceof Error ? error.message : 'Local test failed'); process.exitCode = 1 })
